In [1]:
from Bio import SeqIO, motifs
from Bio.Seq import Seq
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from collections import Counter
import shutil
import os
import csv
from io import StringIO
import random
import re
from Bio.SeqRecord import SeqRecord

from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("7_10000_try.csv")
protein_ID_list = []

for i in range(len(df)):
    protein_ID_list.append(df.loc[i,"Uniprot_ID"])
    
protein_ID_list = list(dict.fromkeys(protein_ID_list))
    
directory = '4_Positive_data/'
file_name = []

for name in protein_ID_list:
    temp = False
    for filename in os.listdir(directory):
        if name in filename:
            file_name.append(filename)
            temp = True
    if temp == False:
        print(name)

In [10]:
df = df[df['Uniprot_ID'] != "P48743"]
df.reset_index(drop=True, inplace=True)

In [9]:
embeddings_0 = {}
embeddings_33 = {}

for file in file_name:
    a = torch.load('human_650m/' + file)
    embeddings_0[a['label'].split('|')[1]] = (a['mean_representations'][0].tolist())
    embeddings_33[a['label'].split('|')[1]] = (a['mean_representations'][0].tolist())
    
df['protein_sequence_emb'] = ''
protein_sequence_emb = []
for i in range(len(df)):
    temp = embeddings_0[df['Uniprot_ID'][i]]
    protein_sequence_emb.append(temp)

df['protein_sequence_emb'] = protein_sequence_emb

In [ ]:
df['DNA_Sequence_encoding'] = ''
alphabet = 'ATCGX'
for n in range(len(df)):
    input_string = df['DNA_Sequence'][n]

    char_to_index = {char: i for i, char in enumerate(alphabet)}

    one_hot_matrix = np.zeros((len(input_string), len(alphabet)),dtype=int)

    for i, char in enumerate(input_string):
        if char in char_to_index:
            one_hot_matrix[i, char_to_index[char]] = 1
        else:
            print("error!!!!!")
            break
    one_hot_matrix = one_hot_matrix.astype(str)
    
    chac_list = []
    for i in range(len(one_hot_matrix)):
        chac = ''
        for j in range(len(one_hot_matrix[i])):
            chac += one_hot_matrix[i][j]
        chac_list.append(chac)

    result = ''
    for a in range(len(chac_list)):
        result += chac_list[a]
    df['DNA_Sequence_encoding'][n] = result
    #print(n) 
    
q = 1
for i in range(55):
    azxsd = []
    col_name = str(1280 + i)
    print(i)
    for n in range(len(asdfghjkl)):
        azxsd.append(df['DNA_Sequence_encoding'][n][i])
    asdfghjkl[col_name] =  azxsd
    
data = {
    'Row0': df['protein_sequence_emb'][0]
}
asdfghjkl = pd.DataFrame.from_dict(data, orient='index')

for i in range(len(df))[1:]:
    name = (f"Row{i}")
    asdfghjkl.loc[name] = df['protein_sequence_emb'][i]

In [ ]:
from gensim.models import Word2Vec

result = {}
for i in range(len(df)):
    temp_gen = []
    sequences = [df['DNA_Sequence'][i]]

    k_mer_size = 3
    k_mers = [''.join(seq[i:i+k_mer_size]) for seq in sequences for i in range(len(seq) - k_mer_size + 1)]

    model = Word2Vec([k_mers], vector_size=11, window=5, min_count=1, workers=4)

    for k_mer in k_mers:
        temp_gen +=  model.wv[k_mer].tolist()
        
    result[i] = temp_gen

for i in range(99):
    col_name = str(1335 + i)
    print(i)
    asdfghjkl[col_name] =  temp_dff[i].tolist()

In [81]:
#asdfghjkl.to_csv('10.9_factor.csv', index=False, encoding='utf-8-sig')

In [24]:
asdfghjkl = pd.read_csv("7_10000_features.csv")
asdfghjkl['Label'] = df['Label']

In [10]:
asdfghjkl

,0,1,2,3,4,5,6,7,8,9,...,1425,1426,1427,1428,1429,1430,1431,1432,1433,Label
0,-0.000844,-0.014036,-0.015465,-0.012514,-0.023681,-0.008265,-0.002055,-0.016170,-0.020259,-0.022946,...,0.046394,0.081902,-0.084572,-0.064698,0.058717,0.081573,-0.045595,-0.034212,0.067095,0
1,-0.018373,-0.022141,-0.023991,-0.019311,-0.021805,-0.008230,-0.004362,-0.022833,-0.007556,-0.020092,...,0.059582,-0.044183,-0.016509,0.026151,0.009017,-0.075320,-0.085898,0.066471,0.046093,0
2,0.001114,-0.010149,-0.016904,-0.019715,-0.017386,-0.005834,-0.007648,-0.021245,-0.031576,-0.009354,...,0.046394,0.081902,-0.084572,-0.064698,0.058717,0.081573,-0.045595,-0.034212,0.067095,1
3,-0.015268,-0.007109,-0.015873,-0.012890,-0.022528,0.001145,-0.001635,-0.025455,-0.017402,-0.023978,...,0.046394,0.081902,-0.084572,-0.064698,0.058717,0.081573,-0.045595,-0.034212,0.067095,0
4,-0.011762,-0.017276,-0.022208,-0.017101,-0.010692,-0.002517,-0.003789,-0.025275,-0.029589,-0.038132,...,0.046394,0.081902,-0.084572,-0.064698,0.058717,0.081573,-0.045595,-0.034212,0.067095,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9908,-0.022664,-0.013557,-0.018619,-0.008504,-0.022804,-0.010535,-0.000848,-0.024650,-0.016125,-0.025386,...,0.059582,-0.044183,-0.016509,0.026151,0.009017,-0.075320,-0.085898,0.066471,0.046093,1
9909,-0.020185,-0.010761,-0.022601,-0.025691,-0.018874,-0.003058,-0.007401,-0.025681,-0.020910,-0.019722,...,0.046394,0.081902,-0.084572,-0.064698,0.058717,0.081573,-0.045595,-0.034212,0.067095,0
9910,-0.017165,-0.014091,-0.032369,-0.025717,-0.011411,-0.004130,-0.013824,-0.030792,-0.031538,-0.025976,...,0.059582,-0.044183,-0.016509,0.026151,0.009017,-0.075320,-0.085898,0.066471,0.046093,0
9911,0.001114,-0.010149,-0.016904,-0.019715,-0.017386,-0.005834,-0.007648,-0.021245,-0.031576,-0.009354,...,0.046394,0.081902,-0.084572,-0.064698,0.058717,0.081573,-0.045595,-0.034212,0.067095,0
9912,-0.014038,-0.014724,-0.018645,-0.010333,-0.018876,-0.004725,-0.003228,-0.025389,-0.022467,-0.027934,...,0.059582,-0.044183,-0.016509,0.026151,0.009017,-0.075320,-0.085898,0.066471,0.046093,0

In [11]:
from pycaret.classification import *
s = ClassificationExperiment()
s.setup(asdfghjkl, target = 'Label', session_id = 123)

In [ ]:
best = s.compare_models(n_select=-1)

Initiated  . . . . . . . . . . . . . . . . . .             16:52:24
Status     . . . . . . . . . . . . . . . . . .     Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  CatBoost Classifier

Processing:   0%|          | 0/69 [00:00<?, ?it/s]